{
    "ResultCode":"0",
    "ResultNum":"1",
    "Result":[
        {
            "SrcID":"48206",
            "ResultURL":"http://m.bj.bendibao.com/kaixue.php?url=aHR0cDovL20uY2QuYmVuZGliYW8uY29tL25ld3MvZ2VsaXpoZW5nY2UvYWxsLnBocD9zcmM9YmFpZHUmbGVhdmVjaXR5PXN1aW5pbmc%3D",
            "NeedMergeURL":[
                "http://m.bj.bendibao.com/kaixue.php?url=aHR0cDovL20uY2QuYmVuZGliYW8uY29tL25ld3MvZ2VsaXpoZW5nY2UvYWxsLnBocD9zcmM9YmFpZHUmbGVhdmVjaXR5PXN1aW5pbmc%3D",
                "http://m.bj.bendibao.com/kaixue.php?url=aHR0cDovL20uY2QuYmVuZGliYW8uY29tL25ld3MvZ2VsaXpoZW5nY2UvZmVuZ3hpYW5taW5nZGFuLnBocD9zcmM9YmFpZHU%3D",
                "http://m.bj.bendibao.com/kaixue.php?url=aHR0cDovL20uY2QuYmVuZGliYW8uY29tL25ld3MvemlqaWFjaHV4aW5nLz9zcmM9YmFpZHU%3D",
                "http://m.bj.bendibao.com/kaixue.php?url=aHR0cDovL20uY2QuYmVuZGliYW8uY29tL25ld3MvaGVzdWFuamlhbmNlLz9zcmM9YmFpZHU%3D"
            ],
            "Weight":"3",
            "ClickNeed":"1",
            "SubResult":[

            ],
            "SubResNum":"0",
            "Title":"成都到遂宁出行政策",
            "TimeFactor":"1660756272",
            "RecoverCacheTime":"0",
            "StrategyInfo":"0",
            "Degree":"3",
            "SubClass":"0",
            "Pos":"-1",
            "Place":"0",
            "Sort":"1",
            "StarModelScore":[
                {
                    "model_name":"intervene",
                    "model_score":"1000"
                }
            ],
            "DisplayData":{
                "StdStg":"48206",
                "StdStl":"0",
                "strategy":{
                    "ctplOrPhp":"1"
                },
                "resultData":{
                    "tplData":{
                        "title":"成都到遂宁出行政策-",
                        "schema_title":"",
                        "provider":[
                            {
                                "jump_url":Object{...},
                                "title":"成都-遂宁出行政策",
                                "subTitle":"科学防疫·伴你安全出行",
                                "leftVal":"成都",
                                "rightVal":"遂宁",
                                "timeLine":[
                                    {
                                        "cityLevel":"1",
                                        "textLineProps":{
                                            "text":"出成都",
                                            "label":"低风险"
                                        },
                                        "time":"数据更新时间：2022-08-18",
                                        "textInfo":"成都市全域无风险区，市民朋友可正常出行，离蓉无需核酸检测报告；但如需离蓉，核酸检测按目的地城市要求执行。",
                                        "url":Object{...},
                                        "tabList":[

                                        ]
                                    },
                                    {
                                        "cityLevel":"1",
                                        "textLineProps":{
                                            "text":"进遂宁",
                                            "label":"低风险"
                                        },
                                        "time":"数据更新时间：2022-08-18",
                                        "url":Object{...},
                                        "tabList":[
                                            {
                                                "text":"低风险地区",
                                                "contentList":[
                                                    "提前报备",
                                                    "三天两检"
                                                ],
                                                "extra":"（返）川人员，应提前向目的地社区（村）登记报备。 对有低风险区7天旅居史的人员，3天内完成两次核酸检测，并做好健康监测。 中、高风险区所在县（市、区、旗）的其他地区为低风险区。"
                                            },
                                            {
                                                "text":"中风险地区",
                                                "contentList":[
                                                    "提前报备",
                                                    "7天居家隔离",
                                                    "隔离第1、4、7天做核酸"
                                                ],
                                                "extra":"近7天内有本土疫情发生的县（市、区、旗）旅居史的来（返）川人员，应提前向目的地社区（村）登记报备。 对有中风险区7天旅居史的来（返）川人员，采取7天居家隔离医学观察，在居家隔离第1、4、7天各开展一次核酸检测；如不具备居家隔离医学观察条件，采取集中隔离医学观察；管理期限自离开风险区域算起。 病例和无症状感染者停留和活动一定时间，且可能具有疫情传播风险的工作地和活动地等区域，划为中风险区，风险区域范围根据流调研判结果划定。"
                                            },
                                            {
                                                "text":"高风险地区",
                                                "contentList":[
                                                    "提前报备",
                                                    "7天集中隔离",
                                                    "隔离第1、2、3、5、7天做核酸"
                                                ],
                                                "extra":"近7天内有本土疫情发生的县（市、区、旗）旅居史的来（返）川人员，应提前向目的地社区（村）登记报备。 对有高风险区7天旅居史的来（返）川人员，采取7天集中隔离医学观察，在集中隔离第1、2、3、5、7天各开展一次核酸检测；管理期限自离开风险区域算起。 病例和无症状感染者居住地，以及活动频繁且疫情传播风险较高的工作地和活动地等区域，划为高风险区。风险区域范围根据流调研判结果划定。"
                                            }
                                        ]
                                    }
                                ],
                                "slinkList":[
                                    {
                                        "text":"风险等级",
                                        "url":{
                                            "src":"http://m.bj.bendibao.com/kaixue.php?url=aHR0cDovL20uY2QuYmVuZGliYW8uY29tL25ld3MvZ2VsaXpoZW5nY2UvZmVuZ3hpYW5taW5nZGFuLnBocD9zcmM9YmFpZHU%3D",
                                            "params":{
                                                "is_xcx":"0",
                                                "cyc":"1",
                                                "xcx_params":{
                                                    "xcx_url":"http://m.bj.bendibao.com/kaixue.php?url=aHR0cDovL20uY2QuYmVuZGliYW8uY29tL25ld3MvZ2VsaXpoZW5nY2UvZmVuZ3hpYW5taW5nZGFuLnBocD9zcmM9YmFpZHU%3D",
                                                    "xcx_appkey":"",
                                                    "xcx_path":"/kaixue.php",
                                                    "xcx_from":"1081000900000000",
                                                    "xcx_query":"url=aHR0cDovL20uY2QuYmVuZGliYW8uY29tL25ld3MvZ2VsaXpoZW5nY2UvZmVuZ3hpYW5taW5nZGFuLnBocD9zcmM9YmFpZHU%3D"
                                                }
                                            }
                                        }
                                    },
                                    {
                                        "text":"交通政策",
                                        "url":{
                                            "src":"http://m.bj.bendibao.com/kaixue.php?url=aHR0cDovL20uY2QuYmVuZGliYW8uY29tL25ld3MvemlqaWFjaHV4aW5nLz9zcmM9YmFpZHU%3D",
                                            "params":{
                                                "is_xcx":"0",
                                                "cyc":"1",
                                                "xcx_params":{
                                                    "xcx_url":"http://m.bj.bendibao.com/kaixue.php?url=aHR0cDovL20uY2QuYmVuZGliYW8uY29tL25ld3MvemlqaWFjaHV4aW5nLz9zcmM9YmFpZHU%3D",
                                                    "xcx_appkey":"",
                                                    "xcx_path":"/kaixue.php",
                                                    "xcx_from":"1081000900000000",
                                                    "xcx_query":"url=aHR0cDovL20uY2QuYmVuZGliYW8uY29tL25ld3MvemlqaWFjaHV4aW5nLz9zcmM9YmFpZHU%3D"
                                                }
                                            }
                                        }
                                    },
                                    {
                                        "text":"核酸检测",
                                        "url":{
                                            "src":"http://m.bj.bendibao.com/kaixue.php?url=aHR0cDovL20uY2QuYmVuZGliYW8uY29tL25ld3MvaGVzdWFuamlhbmNlLz9zcmM9YmFpZHU%3D",
                                            "params":{
                                                "is_xcx":"0",
                                                "cyc":"1",
                                                "xcx_params":{
                                                    "xcx_url":"http://m.bj.bendibao.com/kaixue.php?url=aHR0cDovL20uY2QuYmVuZGliYW8uY29tL25ld3MvaGVzdWFuamlhbmNlLz9zcmM9YmFpZHU%3D",
                                                    "xcx_appkey":"",
                                                    "xcx_path":"/kaixue.php",
                                                    "xcx_from":"1081000900000000",
                                                    "xcx_query":"url=aHR0cDovL20uY2QuYmVuZGliYW8uY29tL25ld3MvaGVzdWFuamlhbmNlLz9zcmM9YmFpZHU%3D"
                                                }
                                            }
                                        }
                                    }
                                ],
                                "url_trans_feature":{
                                    "ala_peak":{
                                        "bgColor":"#0C868E",
                                        "type":"1"
                                    }
                                },
                                "_site_sub_url_arr":[
                                    "http://m.bj.bendibao.com/kaixue.php?url=aHR0cDovL20uY2QuYmVuZGliYW8uY29tL25ld3MvZ2VsaXpoZW5nY2UvYWxsLnBocD9zcmM9YmFpZHUmbGVhdmVjaXR5PXN1aW5pbmc%3D",
                                    "http://m.bj.bendibao.com/kaixue.php?url=aHR0cDovL20uY2QuYmVuZGliYW8uY29tL25ld3MvZ2VsaXpoZW5nY2UvZmVuZ3hpYW5taW5nZGFuLnBocD9zcmM9YmFpZHU%3D",
                                    "http://m.bj.bendibao.com/kaixue.php?url=aHR0cDovL20uY2QuYmVuZGliYW8uY29tL25ld3MvemlqaWFjaHV4aW5nLz9zcmM9YmFpZHU%3D",
                                    "http://m.bj.bendibao.com/kaixue.php?url=aHR0cDovL20uY2QuYmVuZGliYW8uY29tL25ld3MvaGVzdWFuamlhbmNlLz9zcmM9YmFpZHU%3D",
                                    "http://m.bj.bendibao.com/kaixue.php?url=aHR0cDovL20uY2QuYmVuZGliYW8uY29tL25ld3MvZ2VsaXpoZW5nY2UvYWxsLnBocD9zcmM9YmFpZHUmbGVhdmVjaXR5PXN1aW5pbmc%3D",
                                    "http://m.bj.bendibao.com/kaixue.php?url=aHR0cDovL20uY2QuYmVuZGliYW8uY29tL25ld3MvZ2VsaXpoZW5nY2UvYWxsLnBocD9zcmM9YmFpZHUmbGVhdmVjaXR5PXN1aW5pbmc%3D"
                                ],
                                "is_xcx":"0",
                                "app_src_url":"http://m.bj.bendibao.com/kaixue.php?url=aHR0cDovL20uY2QuYmVuZGliYW8uY29tL25ld3MvZ2VsaXpoZW5nY2UvYWxsLnBocD9zcmM9YmFpZHUmbGVhdmVjaXR5PXN1aW5pbmc%3D",
                                "intent":{
                                    "tool_name":""
                                },
                                "time_factor":"1660756272",
                                "appKey":"",
                                "appIcon":"https://mbs1.bdstatic.com/searchbox/mappconsole/image/20200721/58692cf6-6d58-4e44-90dd-3d3530f43bb4.png",
                                "appName":"本地宝"
                            },
                            {
                                "jump_url":{
                                    "src":"https://a2j1a3.smartapps.cn/doctor/pages/epidemic/index/index?src=baidu",
                                    "params":{
                                        "is_xcx":"0",
                                        "cyc":"1",
                                        "xcx_params":{
                                            "xcx_url":"https://a2j1a3.smartapps.cn/doctor/pages/epidemic/index/index?src=baidu",
                                            "xcx_appkey":"15mYVDCHPaBY18X88nVGRgEXC4PzfVyw",
                                            "xcx_path":"/doctor/pages/epidemic/index/index",
                                            "xcx_from":"1081000900000000",
                                            "xcx_query":"src=baidu"
                                        }
                                    }
                                },
                                "title":"成都出行政策",
                                "subTitle":"科学防疫·伴你安全出行",
                                "leftVal":"成都",
                                "rightVal":"遂宁",
                                "url_trans_feature":{
                                    "ala_peak":{
                                        "bgColor":"#0C868E",
                                        "type":"1"
                                    }
                                },
                                "timeLine":[
                                    {
                                        "cityLevel":"",
                                        "textLineProps":{
                                            "text":"离开成都",
                                            "label":""
                                        },
                                        "time":"政策发布时间: 2022年8月17日12时",
                                        "textInfo":"此地区暂无特殊疫情防控政策措施",
                                        "url":{
                                            "src":"https://a2j1a3.smartapps.cn/doctor/pages/epidemic/index/index?src=baidu&chufa_city=成都&mudi_city=遂宁",
                                            "params":{
                                                "is_xcx":"0",
                                                "cyc":"1",
                                                "xcx_params":{
                                                    "xcx_url":"https://a2j1a3.smartapps.cn/doctor/pages/epidemic/index/index?src=baidu&chufa_city=成都&mudi_city=遂宁",
                                                    "xcx_appkey":"15mYVDCHPaBY18X88nVGRgEXC4PzfVyw",
                                                    "xcx_path":"/doctor/pages/epidemic/index/index",
                                                    "xcx_from":"1081000900000000",
                                                    "xcx_query":"src=baidu&chufa_city=成都&mudi_city=遂宁"
                                                }
                                            }
                                        },
                                        "tabList":[

                                        ]
                                    },
                                    {
                                        "cityLevel":"",
                                        "textLineProps":{
                                            "text":"进入遂宁",
                                            "label":""
                                        },
                                        "time":"政策发布时间: 2022年8月17日12时",
                                        "textInfo":"1.从国内省外及境外来(返）遂人员和“四川天府健康通”为红码、黄码的人员，应在2小时内主动向所在地村（社区)、单位、酒店报备，积极配合落实核酸检测、隔离管控、健康监测等疫情防控措施。\n\n2.省外来（返）遂人员免费进行1次核酸检测。\n\n3.从市外入境解除集中隔离后来（返）遂人员或受邀入遂团队，凡到达我市时入境时间不满21天的，由属地闭环接送至集中隔离场所，实行集中隔离直至满21天后，再进行7天居家健康监测。\n\n4.有中高风险地区旅居史来（返）遂人员实行集中隔离直至离开风险区满14天；有中高风险地区所在乡镇（街道）旅居史来（返）遂人员实行集中隔离直至离开风险区所在乡镇（街道）满7天；有中高风险地区所在县（市、区、旗）其他乡镇旅居史来（返）遂人员（不含直辖市），实行居家健康监测直至离开风险区所在县（市、区、旗）满7天；对有中高风险地区所在地市其他县（市、区、旗）和有中高风险地区所在直辖市的县（区）其他乡镇（街道）旅居史的来(返)遂人员，需提供48小时内核酸阴性证明，到达市内目的地后24小时内再进行1次核酸检测，如不能提供48小时内核酸阴性证明，需在入遂后实施3天内2次(间隔24小时)核酸检测。对有本土感染者但未划定中高风险地区的县（市、区、旗）旅居史的来(返)遂人员，需提供48小时内核酸阴性证明，到达市内目的地后24小时内再进行1次核酸检测，如不能提供48小时内核酸阴性证明，需在入遂后实施3天内2次(间隔24小时)核酸检测。",
                                        "url":{
                                            "src":"https://a2j1a3.smartapps.cn/doctor/pages/epidemic/index/index?src=baidu&chufa_city=成都&mudi_city=遂宁",
                                            "params":{
                                                "is_xcx":"0",
                                                "cyc":"1",
                                                "xcx_params":{
                                                    "xcx_url":"https://a2j1a3.smartapps.cn/doctor/pages/epidemic/index/index?src=baidu&chufa_city=成都&mudi_city=遂宁",
                                                    "xcx_appkey":"15mYVDCHPaBY18X88nVGRgEXC4PzfVyw",
                                                    "xcx_path":"/doctor/pages/epidemic/index/index",
                                                    "xcx_from":"1081000900000000",
                                                    "xcx_query":"src=baidu&chufa_city=成都&mudi_city=遂宁"
                                                }
                                            }
                                        },
                                        "tabList":[

                                        ]
                                    }
                                ],
                                "slinkList":[
                                    {
                                        "text":"核酸检测结果",
                                        "url":{
                                            "src":"https://a2j1a3.smartapps.cn/doctor/pages/nucleate/form/index",
                                            "params":{
                                                "is_xcx":"0",
                                                "cyc":"1",
                                                "xcx_params":{
                                                    "xcx_url":"https://a2j1a3.smartapps.cn/doctor/pages/nucleate/form/index",
                                                    "xcx_appkey":"15mYVDCHPaBY18X88nVGRgEXC4PzfVyw",
                                                    "xcx_path":"/doctor/pages/nucleate/form/index",
                                                    "xcx_from":"1081000900000000",
                                                    "xcx_query":""
                                                }
                                            }
                                        }
                                    },
                                    {
                                        "text":"疫情风险等级",
                                        "url":{
                                            "src":"https://a2j1a3.smartapps.cn/publicService/pages/riskGrade/riskGrade",
                                            "params":{
                                                "is_xcx":"0",
                                                "cyc":"1",
                                                "xcx_params":{
                                                    "xcx_url":"https://a2j1a3.smartapps.cn/publicService/pages/riskGrade/riskGrade",
                                                    "xcx_appkey":"15mYVDCHPaBY18X88nVGRgEXC4PzfVyw",
                                                    "xcx_path":"/publicService/pages/riskGrade/riskGrade",
                                                    "xcx_from":"1081000900000000",
                                                    "xcx_query":""
                                                }
                                            }
                                        }
                                    },
                                    {
                                        "text":"各地咨询电话",
                                        "url":{
                                            "src":"https://a2j1a3.smartapps.cn/doctor/pages/epidemic/phone/phone",
                                            "params":{
                                                "is_xcx":"0",
                                                "cyc":"1",
                                                "xcx_params":{
                                                    "xcx_url":"https://a2j1a3.smartapps.cn/doctor/pages/epidemic/phone/phone",
                                                    "xcx_appkey":"15mYVDCHPaBY18X88nVGRgEXC4PzfVyw",
                                                    "xcx_path":"/doctor/pages/epidemic/phone/phone",
                                                    "xcx_from":"1081000900000000",
                                                    "xcx_query":""
                                                }
                                            }
                                        }
                                    }
                                ],
                                "_site_sub_url_arr":[
                                    "https://a2j1a3.smartapps.cn/doctor/pages/epidemic/index/index?src=baidu",
                                    "https://a2j1a3.smartapps.cn/doctor/pages/nucleate/form/index",
                                    "https://a2j1a3.smartapps.cn/publicService/pages/riskGrade/riskGrade",
                                    "https://a2j1a3.smartapps.cn/doctor/pages/epidemic/phone/phone",
                                    "https://a2j1a3.smartapps.cn/doctor/pages/epidemic/index/index?src=baidu&chufa_city=成都&mudi_city=遂宁",
                                    "https://a2j1a3.smartapps.cn/doctor/pages/epidemic/index/index?src=baidu&chufa_city=成都&mudi_city=遂宁"
                                ],
                                "is_xcx":"0",
                                "app_src_url":"https://a2j1a3.smartapps.cn/doctor/pages/epidemic/index/index?src=baidu&chufa_city=成都&mudi_city=遂宁",
                                "intent":{
                                    "tool_name":""
                                },
                                "time_factor":"1660736914",
                                "appKey":"15mYVDCHPaBY18X88nVGRgEXC4PzfVyw",
                                "appIcon":"https://cityservice-hb.cdn.bcebos.com/amis/img/745829739e82.png",
                                "appName":"国务院客户端"
                            }
                        ],
                        "url_na_params_arr":[

                        ],
                        "isXcx":"0",
                        "sitestatistics":[
                            "2003685|0|http://m.bj.bendibao.com/kaixue.php?url=aHR0cDovL20uY2QuYmVuZGliYW8uY29tL25ld3MvZ2VsaXpoZW5nY2UvYWxsLnBocD9zcmM9YmFpZHUmbGVhdmVjaXR5PXN1aW5pbmc%3D|d64708aa4e983c324d0a666ba7ce7110",
                            "2003686|1|https://a2j1a3.smartapps.cn/doctor/pages/epidemic/index/index?src=baidu&chufa_city=成都&mudi_city=遂宁|17523019149db676a306378d62bba719"
                        ],
                        "StdStl":"0",
                        "feedback_content":{
                            "suggest":{
                                "is_show":"1",
                                "title":"您遇到了什么问题",
                                "feedback_type":"",
                                "content":[
                                    {
                                        "appid":"219412",
                                        "text":"内容不是最新的",
                                        "emptyEnable":"0",
                                        "contactRequire":"0",
                                        "reason1":"29456",
                                        "reason2":"33945"
                                    },
                                    {
                                        "appid":"219412",
                                        "text":"内容中有错误信息",
                                        "emptyEnable":"0",
                                        "contactRequire":"0",
                                        "reason1":"29456",
                                        "reason2":"33946"
                                    },
                                    {
                                        "appid":"219412",
                                        "text":"这条结果与搜索词无关",
                                        "emptyEnable":"0",
                                        "contactRequire":"0",
                                        "reason1":"29456",
                                        "reason2":"33840"
                                    },
                                    {
                                        "appid":"219412",
                                        "text":"变形、错乱、乱码等问题",
                                        "emptyEnable":"0",
                                        "contactRequire":"0",
                                        "reason1":"29452"
                                    },
                                    {
                                        "appid":"219412",
                                        "text":"其他问题及建议",
                                        "emptyEnable":"0",
                                        "contactRequire":"0",
                                        "reason1":"29462",
                                        "reason2":"30688"
                                    }
                                ]
                            }
                        },
                        "data_source":"AE"
                    },
                    "extData":{
                        "resourceid":"48206"
                    }
                }
            },
            "url_feature_channel":"\u0010\u0016K\u0000\u0000\u0000tmp_url_trans_feature\u0000\u0002\u0000\u0000\u0000\u0010\t!\u0000\u0000\u0000ala_peak\u0000\u0002\u0000\u0000\u0000\bbgColor\u0000#0C868E\u0000\u0002type\u00001\u0000\u0002url_na_use_result\u00001\u0000"
        }
    ],
    "QueryID":"14985831719759295656",
    "query_trans_feature":"\u0010\u0000(\u0000\u0000\u0000\u0001\u0000\u0000\u0000\u0010\n\u0014\u0000\u0000\u0000ambiguity\u0000\u0001\u0000\u0000\u0000\u0014\nintensity\u0000\u0000\u0000\u0000\u0000",
    "disp_data_query_ex":"\u0010\u0000\u0000\u0000\u0006\u0000\u0000\u0000\u0001mock_recall_srcids\u0000\u0000\fgssda_res_srcid\u000048206;5124;\u0000\fgssda_staratlas_srcid\u000048206;5124;\u0000\u0001gssda_gemini_rewrite_info\u0000\u0000\fubs_ab_gssda_res_srcid\u000048206;5124;\u0000\fubs_ab_gssda_staratlas_srcid\u000048206;5124;\u0000",
    "queryDispInfo":"\u0010\u0000/\u0000\u0000\u0000\u0002\u0000\u0000\u0000\u0007gssda_res\u000048206;\u0000\u0001mock_recall_srcids\u0000\u0000"
}